### ISSUE TITLE
[Question] Cannot find module 'dotenv/config'

### ISSUE THREAD

**Issue by RoyaleOne** [stegripe/rawon#1004]
### Describe the bug

on glitch when you import the bot, it always reaches the file limit and fails to start, am i doing something wrong?

### To Reproduce

1.import rawon from github to glitch
2. make changes and refresh

### Expected behavior

to work

### Screenshots

node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module 'dotenv/config'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1280:12)
    at loadPreloadModules (node:internal/bootstrap/pre_execution:476:5)
    at prepareMainThreadExecution (node:internal/bootstrap/pre_execution:77:3)
    at node:internal/main/run_main_module:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

### Operating System

Windows

**Comment by fab1ofx** [comment]
Try uninstall `npm uninstall dotenv` or remove manual on package.json

**Comment by RoyaleOne** [comment]
> Try uninstall `npm uninstall dotenv` or remove manual on package.json

sadly it fixed nothing because im still running out of space, i tried heroku, it lasted 2 days and my account got suspended, tried railway and did not last even 2 seconds because it violated their terms of service too so it didnt even let me run it

**Comment by RoyaleOne** [comment]
alright this is getting on my nerves, i have done so much troubleshooting on glitch and nothing seems to work! someone please help, sometimes it goes further than other times but it always fails

**Comment by fab1ofx** [comment]
> alright this is getting on my nerves, i have done so much troubleshooting on glitch and nothing seems to work! someone please help, sometimes it goes further than other times but it always fails

but can uninstall dotenv?

**Comment by Fab1o0107** [comment]
> alright this is getting on my nerves, i have done so much troubleshooting on glitch and nothing seems to work! someone please help, sometimes it goes further than other times but it always fails

but can uninstall dotenv?

**Comment by fab1ofx** [comment]
If you want this problem to be completed, you can join our [discord server](https://clytage.org/discord).

**Comment by mzrtamp** [comment]
It seems this is not our fault, you can just simply re-fork and re-importing this project to your Glitch.
