### ISSUE TITLE
[Features] Support for French language

### ISSUE THREAD

**Issue by MoustacheOff** [stegripe/rawon#1029]
### Describe the solution you'd like

Add support or explain how to add new languages to the bot.

### Describe alternatives you've considered

I tried to create a new file called fr.json (translated version of the en.json file) to add the French language in .env and I can't make it work.

### Additional context

The language loaded is English instead of the language set in .env.

**Comment by mzrtamp** [comment]
You need to open a pull request first then commiting that changes (add french language), the tutorial is available on the readme file.

Edit: Oops, I think someone removed how to contribute tutorial, I'll think about this later. You can just share your bot's error message (if any) here

**Comment by MoustacheOff** [comment]
@mzrtamp Can you check if the pull request works for your bot, because it's not the case on mine. Spanish seems to work fine so I think there's an issue with the French one.

**Comment by Mednoob** [comment]
@MoustacheOff Issue fixed in [`25a5cb1`](https://github.com/Clytage/rawon/commit/25a5cb17fddc2ef527f46158802e68692e772e47)

**Comment by MoustacheOff** [comment]
> @MoustacheOff Issue fixed in [`25a5cb1`](https://github.com/Clytage/rawon/commit/25a5cb17fddc2ef527f46158802e68692e772e47)

Okay thanks!
