### ISSUE TITLE
[Bug Report] PROMISE_ERR: DiscordAPIError: Unknown Message

### ISSUE THREAD

**Issue by taninsk137** [stegripe/rawon#1047]
### Describe the bug

I get "PROMISE_ERR: DiscordAPIError: Unknown Message"
every time I type the command in the text channel
-play -skip -ping all commands work like normal but it will have some delays
 ex. when playing or queueing the song it will have a delay before the bot plays the music

I think the problem is located in "src/utils/structures/CommandManager.ts"

Windows 10

**Comment by taninsk137** [comment]
I just learned about try & catch now.
Because it tried to use the command but it didn't work
so next, it caught and the command worked
so the code displayed PROMISE to false positive.
(My API ping was around 150-200 ms that's why it fail to try and need to go to catch)

Am I right? The code work perfectly, it is not a bug.

**Comment by Allvaa** [comment]
the cooldown system on these lines probably causes the Unknown Message error
https://github.com/Clytage/rawon/blob/0f22137bdd6d1383525e03cfd2eaa81a8d1f52dc/src/utils/structures/CommandManager.ts#L221-L228
it tries to delete that one message again after it's successfully deleted.

also,
delays are normal things, especially if the server where you host the bot is far from the discord's server
