### ISSUE TITLE
[Features] Add a volume bar with buttons to adjust the volume

### ISSUE THREAD

**Issue by MoustacheOff** [stegripe/rawon#1052]
### Is your feature request related to a problem? Please describe.

Currently, when using the volume command followed by no parameters, the bot says this: Please pause the music instead of setting the volume to **`{volume}`**.

### Describe the solution you'd like

When using /volume, the bot should send a menu similar to the selectmenu from the nowplaying command, with a volume bar and buttons to adjust the volume.

### Additional context

![image](https://user-images.githubusercontent.com/49116367/198011320-6c2d69f2-a989-471e-a5ef-4c714b49eb7d.png)
(here, the bot uses custom emojis)

**Comment by Mednoob** [comment]
Added in [v3.1.0](https://github.com/Clytage/rawon/releases/tag/3.1.0)
