### ISSUE TITLE
[Bug Report] I can't use Volume command and discordjs/voice 0.13.0

### ISSUE THREAD

**Issue by taninsk137** [stegripe/rawon#1056]
I got this error when using volume command
UNHANDLED_REJECTION: TypeError: Cannot read properties of undefined (reading 'volume') 

I tried this package in Glitch project
discordjs/voice 0.13.0
but it need to install sodium or libsodium-wrapper
when i install it will not work loop compile
and it always get error, so i switch back to discordjs/voice 0.11.0

**Comment by MoustacheOff** [comment]
I get the same error when using /volume.
However, the command seems to work with {prefix}volume.

**Comment by MoustacheOff** [comment]
> I tried this package in Glitch project discordjs/voice 0.13.0 but it need to install sodium or libsodium-wrapper when i install it will not work loop compile and it always get error, so i switch back to discordjs/voice 0.11.0

#1036

**Comment by mzrtamp** [comment]
Fixed in [`8f28a4e`](https://github.com/Clytage/rawon/commit/8f28a4e3c9e7c52b99b10d7c4ea18efa1e390cda)
