### ISSUE TITLE
[Bug Report] About command not working

### ISSUE THREAD

**Issue by taninsk137** [stegripe/rawon#1058]
### Describe the bug

[2022-11-03 04:08:19 (+00)] [error]: Error occured while loading AboutCommand.js: Module "file:///app/package.json" is not of type "json" 
(node:2481) ExperimentalWarning: The Node.js specifier resolution in ESM is experimental.
(Use `node --trace-warnings ...` to show where the warning was created)
[2022-11-03 04:08:19 (+00)] [warn]: ExperimentalWarning: The Node.js specifier resolution in ESM is experimental. 

no respond when using {prefix}about

**Comment by MoustacheOff** [comment]
You probably haven't edited package.json correctly.

**Comment by Mednoob** [comment]
@taninsk137 What's the node version you used for running the bot? (you can check it by running `node -v` in your terminal/shell)

**Comment by taninsk137** [comment]
16.14.2

**Comment by MoustacheOff** [comment]
> 16.14.2

@taninsk137 You should install Node.JS LTS version (18.12.0).
What operating system are you using?

**Comment by Mednoob** [comment]
> 16.14.2

Just tried running the bot with that version of node and yes, the bot unable to register `about` command. You should probably change to the current LTS version, as suggested by @MoustacheOff .

**Comment by MoustacheOff** [comment]
@taninsk137 Install Node.js LTS on https://nodejs.org or install it using [`nvm`](https://github.com/nvm-sh/nvm#install--update-script).

**Comment by taninsk137** [comment]
i used Glitch

**Comment by Mednoob** [comment]
Issue fixed in [`3fdf9e1`](https://github.com/Clytage/rawon/commit/3fdf9e1f6afc3ad484b7d4c7e9ab1aff117e0b74)
