### ISSUE TITLE
[Question] Bot not starting on Replit

### ISSUE THREAD

**Issue by 21Z** [stegripe/rawon#1060]
### Describe the bug

bot fails to start with no (proper) error

### Expected behavior

It should work

### Screenshots

![image](https://user-images.githubusercontent.com/69188068/200021457-80df9001-1d93-4f55-8b10-89f46f9e90cd.png)

### Operating System

Linux

**Comment by Mednoob** [comment]
I think it's because of request rate limit, since replit is a shared hosting after all. Try re-creating the project.
