### ISSUE TITLE
[Question] The bot does not see the use of the prefix

### ISSUE THREAD

**Issue by KotvPalt0** [stegripe/rawon#1072]
### Describe the bug

The essence of the problem is as follows. When I call the bot with "!", it does not respond, if it is mentioned, it works as it should (it also works as it should with slash commands). I would like to understand why it does not work through the prefix

### Operating System

Windows

**Comment by Mednoob** [comment]
@KotvPalt0 Hi, try checking the intents of the bot in discord dev page. You have to enable message intent to use prefix.
