### ISSUE TITLE
[Features] Change the activity info when bot is loading

### ISSUE THREAD

**Issue by PixlGalaxy** [stegripe/rawon#1078]
### Is your feature request related to a problem? Please describe.

This will help users to know when they can start using the bot, because when you start the script the bot will automatically appear online, but it will not respond to commands. Thats why i am suggesting this feature.

### Describe the solution you'd like

It will be cool to see the bot status saying Loading or booting while the bot is starting, and when it finishes loading it will add the activity that was set on the .env file.

### Additional context

So the idea will be that when you start the bot, the bot status will show "loading" while it loads all the commands.
![Loading](https://user-images.githubusercontent.com/81576840/204894982-92864307-ee4b-4977-9c62-8cc6b5ad0940.png)

When done loading all the commands and it is ready to receive commands it will change the bot status to the one that was set on the .env file.
![Listening](https://user-images.githubusercontent.com/81576840/204894978-a8954766-1e03-4e3e-acf1-4d173a4a33cb.png)

**Comment by Mednoob** [comment]
@PixlGalaxy Added in [`e88aae4`](https://github.com/Clytage/rawon/commit/e88aae4de58355487bf442c7b2a20de3974f4e2e)
