### ISSUE TITLE
[Bug Report] Search command can't multiply queue

### ISSUE THREAD

**Issue by taninsk137** [stegripe/rawon#1098]
### Describe the bug

after searching some songs
"Please select some music; you can choose more than one using blank space or ,."

I cant select multiple song like what you said
If I entered 1 2 3 or 1,2,3 nothing will happen
but if I entered 1, 2 it will queue the song
but only song #1 will queue, song #2 didn't add to q
sry about my English

**Comment by Mednoob** [comment]
Fixed in [`d67a951`](https://github.com/Clytage/rawon/commit/d67a951203accb338d7a325f9449f12fd6aa61e7)
