### ISSUE TITLE
[Bug Report] YouTube URLs is not working

### ISSUE THREAD

**Issue by Pizzarous** [stegripe/rawon#1113]
### Describe the bug

On **v3.1.0**, YouTube links (youtube.com || youtu.be) do not seem to be working. I Keep getting "**That URL doesn't have any song data.**" error message. Typing the song name, giving just the song ID or using a playlist URL seems to work.
Spotify URLs are working too.

### Screenshots

![image](https://user-images.githubusercontent.com/92325318/210890037-d71e595b-a5ff-432e-aa42-765ddc3ac7fa.png)

![image](https://user-images.githubusercontent.com/92325318/210890168-16411382-f36c-414e-a4a0-321cca2e97fb.png)

![image](https://user-images.githubusercontent.com/92325318/210890257-7251407a-ff7a-499a-bab5-5abc985a39eb.png)

![image](https://user-images.githubusercontent.com/92325318/210890427-cbbfb0f0-0831-424b-b611-c9fb5b282d8b.png)

### Operating System

Windows 11

**Comment by MoustacheOff** [comment]
Did you clone the latest commit?
Don't download via the "Releases" tab.

**Comment by Pizzarous** [comment]
Yes after posting this I went ahead and cloned the whole latest commit, but I am getting the same issue as before

**Comment by MoustacheOff** [comment]
> Yes after posting this I went ahead and cloned the whole latest commit, but I am getting the same issue as before

I had the same issue a while ago, but I don't really remember how I fixed it.

**Comment by mzrtamp** [comment]
Fixed in #1116
