### ISSUE TITLE
[Bug Report] Spotify playlist queue shuffling error

### ISSUE THREAD

**Issue by Hyadawild** [stegripe/rawon#1129]
### Describe the bug

when i add playlist spotify in queue will shuffle not same from spotify queue 

### Operating System

Windows

**Comment by mzrtamp** [comment]
Hello, if you want to follow up this issue, can you provide us any screenshots I think? So we can debug about this error.

**Comment by Hyadawild** [comment]
I Will send the screenshot, sorry for the inconvenience
