### ISSUE TITLE
[Bug Report] Playlist command

### ISSUE THREAD

**Issue by projectrift** [stegripe/rawon#1150]
### Describe the bug

When i use any playlist command, it just displays "The application did not respond" what should i do?

### Screenshots

![Screenshot_4](https://user-images.githubusercontent.com/85791482/220424624-bc9bcda6-4fd0-414c-90f9-72a7c552f843.png)

### Operating System

Windows

**Comment by Mednoob** [comment]
@projectrift Rawon does not have `playlist` command. Maybe that slash command left from when you run another code using the same bot.

**Comment by mzrtamp** [comment]
That's probably not a slash from Rawon.

**Comment by projectrift** [comment]
> @projectrift Rawon does not have `playlist` command. Maybe that slash command left from when you run another code using the same bot.

Maybe, although when i ran other code meanwhile rawon broke for me, "playlist" command dissapeared and when i fixed rawon and it registered commands. The "playlist" command wasn't there anymore so i bet it was just some command being there.
