### ISSUE TITLE
[Bug Report] Cannot establish a voice connection

### ISSUE THREAD

**Issue by rodritwm** [stegripe/rawon#1158]
### Describe the bug

After 50ish seconds the bot displays this error:
[error]: PLAY_ERR: AbortError: Cannot establish a voice connection within 15 seconds.
Node version: v16.19.1
Npm version: 8.19.3

### Operating System

Ubuntu 22.04.2 LTS

**Comment by Pizzarous** [comment]
Hi there,

I believe this issue is related to the change described in [this comment](https://github.com/discordjs/discord.js/issues/9185#issuecomment-1451442314). 

My issue was that the bot would play the song until 58 seconds and then just stop.
I managed to find a workaround by using the solution provided in [this comment](https://github.com/discordjs/discord.js/issues/9185#issuecomment-1452514375).

Specifically, I added the following code after the declaration of `const connection` of `handleVideos.ts`:

```javascript
connection.on('stateChange', (oldState, newState) => {
    const oldNetworking = Reflect.get(oldState, 'networking');
    const newNetworking = Reflect.get(newState, 'networking');

    // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
    const networkStateChangeHandler = (oldNetworkState: any, newNetworkState: any) => {
        const newUdp = Reflect.get(newNetworkState, 'udp');
        // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
        clearInterval(newUdp?.keepAliveInterval);
    }

    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
    oldNetworking?.off('stateChange', networkStateChangeHandler);
    // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
    newNetworking?.on('stateChange', networkStateChangeHandler);
});
```

I'm not sure if this is a temporary fix or if the solution will be more elegant than this but for the time being it's working for me.
Hopefully this helps both you and the devs.

**Comment by rodritwm** [comment]
> Hi there,
> 
> I believe this issue is related to the change described in [this comment](https://github.com/discordjs/discord.js/issues/9185#issuecomment-1451442314).
> 
> My issue was that the bot would play the song until 58 seconds and then just stop. I managed to find a workaround by using the solution provided in [this comment](https://github.com/discordjs/discord.js/issues/9185#issuecomment-1452514375).
> 
> Specifically, I added the following code after the declaration of `const connection` of `handleVideos.ts`:
> 
> ```js
> connection.on('stateChange', (oldState, newState) => {
>     const oldNetworking = Reflect.get(oldState, 'networking');
>     const newNetworking = Reflect.get(newState, 'networking');
> 
>     // eslint-disable-next-line @typescript-eslint/explicit-function-return-type
>     const networkStateChangeHandler = (oldNetworkState: any, newNetworkState: any) => {
>         const newUdp = Reflect.get(newNetworkState, 'udp');
>         // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
>         clearInterval(newUdp?.keepAliveInterval);
>     }
> 
>     // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
>     oldNetworking?.off('stateChange', networkStateChangeHandler);
>     // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-call
>     newNetworking?.on('stateChange', networkStateChangeHandler);
> });
> ```
> 
> I'm not sure if this is a temporary fix or if the solution will be more elegant than this but for the time being it's working for me. Hopefully this helps both you and the devs.

Thank you so much, gonna give it a try soon!!

**Comment by Hyadawild** [comment]
> 

i was trying and it same. the bot playing but after few sec stop

**Comment by fab1ofx** [comment]
I will open a PR now, but I will test it first before merging it into the main branch.
