### ISSUE TITLE
[Bug Report] "Selectmenu" is not working

### ISSUE THREAD

**Issue by madscientista** [stegripe/rawon#1166]
### Describe the bug

I used the selectmenu option for displaying the buttons but its not showing on the bot itself. What am I doing wrong?

### Operating System

Linux

**Comment by mzrtamp** [comment]
I know this bug because someone reported in on our Discord aswell.
Try using `message` first, we will try to debug this soon once we have a time.

**Comment by madscientista** [comment]
Was confused, solved

**Comment by mzrtamp** [comment]
Hahaha
