### ISSUE TITLE
[Bug Report] Bot won't start

### ISSUE THREAD

**Issue by Barra203** [stegripe/rawon#1172]
### Describe the bug

can't start the bots

### Screenshots

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/container/yt-dlp-utils' is not supported resolving ES modules imported from /home/container/index.js
Did you mean to import ../yt-dlp-utils/index.js?
    at new NodeError (node:internal/errors:372:5)
    at finalizeResolution (node:internal/modules/esm/resolve:401:17)
    at moduleResolve (node:internal/modules/esm/resolve:964:10)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:604:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///home/container/yt-dlp-utils'
}
Node.js v17.9.1

### Operating System

Linux (Pterodactyl)

**Comment by Mednoob** [comment]
how did you run the bot?

**Comment by Mednoob** [comment]
Can you check the startup command used in the ptero server?

**Comment by mzrtamp** [comment]
Please use node v18

**Comment by Barra203** [comment]
i tried use on vs code and this happened
![Screenshot 2023-03-18 231107](https://user-images.githubusercontent.com/102669079/226118472-603b0d79-a0aa-49de-94ac-c01674830de1.png) ( Node.js v18.12.0 )



what should I do?

**Comment by Barra203** [comment]
> Can you check the startup command used in the ptero server?


```if [[ -d .git ]] && [[ 0 == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/node /home/container/index.js```

**Comment by Mednoob** [comment]
> > Can you check the startup command used in the ptero server?
> 
> `if [[ -d .git ]] && [[ 0 == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/node /home/container/index.js`

Can you edit the startup? The bot shouldn't run index.js directly. The startup should be like this
```
if [[ -d .git ]] && [[ 0 == "1" ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then /usr/local/bin/npm install ${NODE_PACKAGES}; fi; if [[ ! -z ${UNNODE_PACKAGES} ]]; then /usr/local/bin/npm uninstall ${UNNODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then /usr/local/bin/npm install; fi; /usr/local/bin/npm run compile; /usr/local/bin/npm run start
```

**Comment by fab1ofx** [comment]
> i tried use on vs code and this happened
> ![Screenshot 2023-03-18 231107](https://user-images.githubusercontent.com/102669079/226118472-603b0d79-a0aa-49de-94ac-c01674830de1.png) ( Node.js v18.12.0 )
> 
> 
> 
> what should I do?

it installs `ffmpeg-static` if the ffmpeg environment doesn't exist

**Comment by Barra203** [comment]
![Screenshot 2023-03-25 134019](https://user-images.githubusercontent.com/102669079/227701443-ee716627-8b2d-4213-9b12-056fb6bac81b.png)
after i download ffmpeg-static, i got this error

**Comment by fab1ofx** [comment]
> ![Screenshot 2023-03-25 134019](https://user-images.githubusercontent.com/102669079/227701443-ee716627-8b2d-4213-9b12-056fb6bac81b.png)
> after i download ffmpeg-static, i got this error

If using pterodactyl? If possible, can you send the pterodactyl startup?

**Comment by Fab1o0107** [comment]
> ![Screenshot 2023-03-25 134019](https://user-images.githubusercontent.com/102669079/227701443-ee716627-8b2d-4213-9b12-056fb6bac81b.png)
> after i download ffmpeg-static, i got this error

If using pterodactyl? If possible, can you send the pterodactyl startup?

**Comment by SysMath** [comment]
Pterodactyl is a docker manager,
If the entrypoint.sh does not support installing ffmpeg it will bug the bot.
Same for git.

I suggest you ask the people proposing pterodactyl to check the content of the chosen docker container.
If these are the default it shouldn't be a problem for git but for ffmpeg you'll have to add a line.

And if it still does not work I invite you to try on NodeJS 16, on my side it works with ...

**Comment by fab1ofx** [comment]
> Pterodactyl is a docker manager,
> If the entrypoint.sh does not support installing ffmpeg it will bug the bot.
> Same for git.
> 
> I suggest you ask the people proposing pterodactyl to check the content of the chosen docker container.
> If these are the default it shouldn't be a problem for git but for ffmpeg you'll have to add a line.
> 
> And if it still does not work I invite you to try on NodeJS 16, on my side it works with ...
> 

ffmpeg for rawon we use ffmpeg-static, if you use ffmpeg from docker directly?

You can use Pterodactyl Images from us.

Alpine: `ghcr.io/clytage/node:16-alpine`
Debian: `ghcr.io/clytage/node:16`

Or you can visit this repo: [Clytage/pterodactyl-images](https://github.com/Clytage/pterodactyl-images)

**Comment by 21Z** [comment]
As stated above, modify your startup command, if not possible use:
https://github.com/21Z/rawon 
(This is tested on VS Code Node.js 19, so do let me know if it worked!)

**Comment by fab1ofx** [comment]
I will close this issue, if there is a problem about this.

You can join our **[Discord Server](https://clytage.org/discord)**!
