### ISSUE TITLE
[Bug Report] Bot Can't Play Music

### ISSUE THREAD

**Issue by nu07** [stegripe/rawon#1182]
### Describe the bug
I Got Error when using Play-dl
sorry if my post is not clear, because this is my first time doing a report

``
![Screenshot 2023-03-31 004635](https://user-images.githubusercontent.com/45446283/228921072-91a422c8-7e59-41e5-800a-8fd56ba0a419.png)

i am using play-dl method while running this app. using docker and node version 18.14.1

### To Reproduce

npm install
npm run build
npm prune --production

### Screenshots

![Screenshot 2023-03-31 004635](https://user-images.githubusercontent.com/45446283/228921421-9ddd0ae6-ebde-4f60-9d2b-0e46f4800e6a.png)

### Operating System

Ubuntu 20.04.03 LTS

**Comment by Mednoob** [comment]
Looking from the error, it looks like the bot got rate-limited. This can happen when the bot has done too much request to youtube. The best you can do is just wait until the rate-limit is off. Usually, it's in an hour.
