### ISSUE TITLE
[Features] Docker support

### ISSUE THREAD

**Issue by mrpinkcat** [stegripe/rawon#1209]
### Is your feature request related to a problem? Please describe.

The containerization is an important point while deploying an application. It ensure deployment consistency and portability on selfhost machine. It also helps to scale the application easily. This is why I think it is important to have a docker image.

### Describe the solution you'd like

I would like to have a docker image for the application. It should be:
 - available on docker hub.
 - based on the latest version of the application.
 - updated when a new version of the application is released.

**Comment by parnavh** [comment]
I am willing to work on this issue if the core maintainers see this as a useful addition

**Comment by mzrtamp** [comment]
> I am willing to work on this issue if the core maintainers see this as a useful addition

We got this, don't worry.
