### ISSUE TITLE
[Bug Report] The music player is already playing to #unknown-channel voice channel

### ISSUE THREAD

**Issue by PixlGalaxy** [stegripe/rawon#1215]
### Describe the bug

If the player encounters an error when trying to play a song, it may get stuck on an unknown channel and cannot be used again unless you restart the bot from the console. No matter how much time passes, the bot will never leave the channel.

One solution may be to add a command to leave the channel where the bot is playing music, forcing it to leave the unknown channel.

### To Reproduce

In my case, I added a song that was age restricted and got an error, then I couldn't use the player on that discord server again until I restarted the bot.

### Expected behavior

The bot will continue to work on other servers but it will be blocked on the server it got the error.

### Screenshots

![image](https://github.com/Clytage/rawon/assets/81576840/25f4a8ea-9c75-4ed5-9372-c23b0ee2fe6a)

### Operating System

Windows Server 2022

**Comment by mzrtamp** [comment]
This is not a bug at all, we just didn't handled this (when `Sign in to confirm your age` error appears) yet

**Comment by PixlGalaxy** [comment]
@mzrtamp Yes but the problem is that the bot stops working and stays in an "#unknown-channel". Maybe creating a "leave" command will fix it.

**Comment by Mednoob** [comment]
You're right. Adding `leave` command to destroy the queue should fix the problem. Will add it to my to-do list along with the `unknown-channel` issue fix.
