### ISSUE TITLE
[Bug Report] help repeat commands doesn't show output as intended in Indonesian

### ISSUE THREAD

**Issue by kyznikov** [stegripe/rawon#1224]
### Describe the bug

_help repeat_ command is not showing in Indonesian but it works just fine in English

### To Reproduce

_help repeat_ command is not showing in Indonesian but it works just fine in English
![image](https://github.com/Clytage/rawon/assets/71540622/d00dbaec-6398-46a4-8941-5e83f40835c2)
When i checked the _language.json_ in _lang,_ the English version shows like this:
![image](https://github.com/Clytage/rawon/assets/71540622/8918517a-b94d-4652-880d-afb1dc5cd514)
Whereas in the Indonesian version, it shows like this:
![image](https://github.com/Clytage/rawon/assets/71540622/0059c861-9d44-4a1c-8d82-cc53297cfc60)

### Expected behavior

the only difference is that the Indonesian version seems to be missing the '' in the _{prefix}_ and the _<{options}>_ is translated to _<{opsi}>,_ so i changed _{prefix}repeat <{opsi}>_ to _'{prefix}'repeat <{options}>_ like every other language
and now it works as it should be
![image](https://github.com/Clytage/rawon/assets/71540622/caf7ceb1-471d-473e-9fd2-c6a71185041a)

### Operating System

Windows

**Comment by Mednoob** [comment]
Fixed in [`47b55c7`](https://github.com/clytage/rawon/commit/47b55c7475687a9fc93ab08751cbf50f3daf6907)
