### ISSUE TITLE
[Bug Report] Docker Container

### ISSUE THREAD

**Issue by LogicalSoIutions** [stegripe/rawon#1239]
### Describe the bug

logical@homeserver:~/musicbot$ docker run -v ./scripts:/app/scripts --env-file ./.env -d ghcr.io/clytage/rawon:latest
Unable to find image 'ghcr.io/clytage/rawon:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/clytage/rawon/manifests/latest": unauthorized.

### To Reproduce

Using docker-compose or docker run

### Operating System

Ubuntu 22.04

**Comment by uberyb** [comment]
I'm getting the same error on debian 13. I think it means the docker image has been made private somehow.

**Comment by satoufuyuki** [comment]
Fixed
