### ISSUE TITLE
[Bug Report] Song stops before it's finished

### ISSUE THREAD

**Issue by foxlet** [stegripe/rawon#1241]
### Describe the bug

When playing music back from YouTube sources, the bot will stop before the end of the track, usually in the middle.

Using the play-dl backend.

### To Reproduce

1. Play song from URL
2. Wait for song to finish
3. Song stops with "Queue has ended"

### Expected behavior

Currently playing song finishes till the end.

### Operating System

Linux

**Comment by mzrtamp** [comment]
Fixed by downgrading the opusscript.
