### ISSUE TITLE
[Bug Report] Not Playing the music

### ISSUE THREAD

**Issue by eloahmorningstar** [stegripe/rawon#1255]
### Describe the bug

when using the music is not playing. as off 8/22/2023

### Expected behavior

should play the music

### Operating System

windows server 2012

**Comment by Mednoob** [comment]
Please explain more about your issue, any screenshot or console error would help

**Comment by warrenrezane** [comment]
Hi, @Mednoob ! When trying to play a song, directly from Spotify and search based, we get this 429 error.
<img width="1422" alt="Screen Shot 2023-08-25 at 6 53 36 PM" src="https://github.com/clytage/rawon/assets/19648576/9e8db94b-629a-4634-9650-1e980f773753">

**Comment by ShockedCoder** [comment]
It means "Too Many Requests".
Sites return this HTTP code when they're rate-limiting you.

**Comment by Mednoob** [comment]
Closing this since this is not an issue from the bot's code and already explained by another user.
