### ISSUE TITLE
[Bug Report] Instantly ends song

### ISSUE THREAD

**Issue by ShockedCoder** [stegripe/rawon#1271]
### Describe the bug

When you play a song, either through query or direct link, it joins the voice chat and plays nothing.

### To Reproduce

1. `docker-compose up`
2. go to vc
3. play any song

### Expected behavior

It plays the song properly

### Screenshots

![image](https://github.com/clytage/rawon/assets/40272709/7773a4a5-7a91-4caf-b676-8a2c3c7c1eb8)

### Operating System

Linux

### Additional context

https://github.com/clytage/rawon/assets/40272709/0d4cf704-5f4b-4eb1-94e5-9b3fee28ee6c

**Comment by fab1ofx** [comment]
try change stream strategy to play-dl

**Comment by ShockedCoder** [comment]
Works great 👍 
Thanks very much.

EDIT: Also, after lookin' around for a little bit, it seems like the `yt-dlp` file which gets downloaded in `scripts` is a zip file, I thought I'd mention it, since the file didn't have the ext on it, so I assumed it may have been unintentional.

**Comment by mzrtamp** [comment]
Duplicate of #1241
