### ISSUE TITLE
[Bug Report] UNSUPPORTED_DIR_IMPORT

### ISSUE THREAD

**Issue by Yuanjie58** [stegripe/rawon#1340]
### Describe the bug

UNSUPPORTED_DIR_IMPORT]: Directory import '/home/runner/rawon/node_modules/date-fns/locale' is not supported resolving ES modules imported from /home/runner/rawon/dist/utils/functions/formatMS.js
Did you mean to import date-fns/locale/index.js? 

### Operating System

Linux

**Comment by Mednoob** [comment]
Well, judging from this and your previous issue, how did you run the bot? Make sure you use `npm run start` instead of directly running `node index.js`.

**Comment by Yuanjie58** [comment]
i run it using npm run start and it fix

**Comment by mzrtamp** [comment]
Duplicate of #1338
