### ISSUE TITLE
[Bug Report] Installation error

### ISSUE THREAD

**Issue by lxndr-rl** [stegripe/rawon#1407]
### Describe the bug

It probably shouldn't be called a bug, however, it would be good to check Rawon's dependencies.

The "Got" dependency requires node 20
https://github.com/sindresorhus/got/releases/tag/v14.0.0

And rawon requires 16
```json
	"engines": {
		"node": ">=16.6.0",
		"npm": ">=7.0.0"
	}
```

Should the node dependency in rawon be changed from version 16 to version 20?

### To Reproduce

1. Clone repo
2. yarn

### Expected behavior

Installation completed

### Operating System

Linux

**Comment by Mednoob** [comment]
Well, based on the package file data, yeah It should be changed. However, I didn't see any issue with the bot running in lower version. So, I didn't change it.

**Comment by lxndr-rl** [comment]
I haven't said it doesn't work, just that perhaps it should be taken into consideration.

**Comment by mzrtamp** [comment]
Closing due to inactivities and less relation.
