### ISSUE TITLE
[Bug Report] Error adding music with youtu.be URLs, cannot read property 'split' of null 

### ISSUE THREAD

**Issue by irfaantx** [stegripe/rawon#357]
![Screenshot_2021-07-13-19-04-30-62](https://user-images.githubusercontent.com/67856365/125448592-d38e73df-9ad5-4478-8efc-50a3339aab39.jpg)

**Comment by mzrtamp** [comment]
Ask about things like this on the [Discord server](https://zhycorp.net/discord) instead of opening an issue.
