### ISSUE TITLE
[Bug Report] Error while playing music

### ISSUE THREAD

**Issue by KTSnowy** [stegripe/rawon#421]
"Error while playing music
Reason: YTDLError: aborted"

It happens around the middle/end of every song I tried.

**Comment by mzrtamp** [comment]
Thanks for your bug report, I'm going about to rebasing this project ASAP, or it will depends to its [original project](https://github.com/Hazmi35/jukebox)

**Comment by KTSnowy** [comment]
I've tested the original project, and it also happens there.

**Comment by mzrtamp** [comment]
Yea I know

**Comment by mzrtamp** [comment]
It's not my fault probably

**Comment by mzrtamp** [comment]
My changes and commits were inconsistent, and it's unstable. So I decided to revert to v4 and turn off versioning which would depend on the original project only. Reclone and rebasing.
