### ISSUE TITLE
[Features] Spotify and SoundCloud support

### ISSUE THREAD

**Issue by rec0de** [stegripe/rawon#446]
Hi!

I was just wondering what happened to Spotify support - going through the repo I can see there were a couple merged pull requests (#235 #236) that got reverted later in #260.

Was there an issue with that implementation or another reason why Spotify support got removed?

Thanks!

**Comment by mzrtamp** [comment]
A simple statement where **I can no longer take care of this feature**, many factors affect it.
All my projects lack maintainers, I can't do this myself, so sorry.

**Comment by rec0de** [comment]
Ok, I thought that might be the reason :) Anyways, thanks for the reply & take care!

(also feel free to close this)

**Comment by mzrtamp** [comment]
Thanks, this will depend on #450

**Comment by mzrtamp** [comment]
I will plan something good with this.

**Comment by KagChi** [comment]
instead of resolving all tracks, what if you create an unresolved one, the track will be resolved when it is played, to reduce rate limit

**Comment by mzrtamp** [comment]
Done in #460
