### ISSUE TITLE
[Question] TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by gmorningman** [stegripe/rawon#455]
Cannot start the server. 
Have pasted my output below.

```
username@server:~/disc-11$ npm start

> disc-11@1.0.0 start /home/username/disc-11
> node start.js

/home/username/disc-11/dist/utils/Logger.js:13
        .replace(/<hour>/g, data.find(({ type }) => type === "hour").value)
                                                                    ^

TypeError: Cannot read property 'value' of undefined
    at formatDateForLogFile (/home/username/disc-11/dist/utils/Logger.js:13:69)
    at createLogger (/home/username/disc-11/dist/utils/Logger.js:39:92)
    at Object.<anonymous> (/home/username/disc-11/dist/main.js:8:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! disc-11@1.0.0 start: `node start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the disc-11@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2021-09-15T01_06_31_541Z-debug.log
username@server:~/disc-11$
```

**Comment by Mednoob** [comment]
Go to `package.json` file and then search for `"node": `. Beside the `"node": `, you will see like `>=` and then some kind of number. That's the version of Node.JS used for running the project. Change the version to `>=14.x`. @gmorningman

**Comment by gmorningman** [comment]
yes it was version issue thank you, for anybody else who may come across this post

I have Ubuntu Server 20.04 installed
Installed node.js by  `sudo apt install nodejs`
This only installs version 10
to install version 14 i download binary file from https://nodejs.org/en/download/
then extract  `tar -xf *node*`
then install by `sudo cp -r ./{lib,share,include,bin} /usr`

**Comment by mzrtamp** [comment]
> yes it was version issue thank you, for anybody else who may come across this post
> 
> I have Ubuntu Server 20.04 installed
> Installed node.js by sudo apt install nodejs
> This only installs version 10
> to install version 14 i download binary file from https://nodejs.org/en/download/
> then extract tar -xf _node_
> then install by sudo cp -r ./{lib,share,include,bin} /usr

Thanks
