### ISSUE TITLE
[Features] Buttons on Now-playing command

### ISSUE THREAD

**Issue by moritzlerch** [stegripe/rawon#471]
This would probably entail slash commands. Slash commands would be fancy overall!

Probably like this: 
![grafik](https://user-images.githubusercontent.com/59474941/134347052-7f854bc2-c9b9-4da4-9781-c1709e601e8b.png)

**Comment by mzrtamp** [comment]
What do you think? @Mednoob

**Comment by Mednoob** [comment]
This is a great feature to add. Thanks for requesting this.

**Comment by mzrtamp** [comment]
Done in #460

**Comment by moritzlerch** [comment]
Thanks!

**Comment by mzrtamp** [comment]
Keep in mind these changes aren't landed yet, just wait for #460 to be merged.
