### ISSUE TITLE
[Features] Add Vote on Skip command

### ISSUE THREAD

**Issue by SouvikUnscripted** [stegripe/rawon#476]
There are times, when there are multiple people in the same voice channel listening to music, someone suddenly comes and ends the music, but the other people want to hear the song, in this time vote skip command will make the work done. - When there are multiple people in the voice channel, the bot will put up a vote to skip the music, instead of skipping the music directly. - The one with the "DJ" role can skip the music directly. (5 people listening to music, there should be 3 skip votes to skip the song, 3 people listening to music, there should be 2 skip votes to skip the song.) - Thanks!

**Comment by mzrtamp** [comment]
Perhaps voteskip?

**Comment by SouvikUnscripted** [comment]
yup, whatever you call it.

**Comment by mzrtamp** [comment]
Done in #460

**Comment by cattaneod** [comment]
This isn't working for me. Everyone can skip without vote, even without DJ role and not the person who requested the song.

**Comment by Mednoob** [comment]
> This isn't working for me. Everyone can skip without vote, even without DJ role and not the person who requested the song.

How many user that was in the VC (including you, but not including the bot)?

**Comment by cattaneod** [comment]
> How many user that was in the VC (including you, but not including the bot)?

There were four people in the channel.

**Comment by Mednoob** [comment]
> > How many user that was in the VC (including you, but not including the bot)?
> 
> There were four people in the channel.

Does the person who used the `skip` command have `Manage Guild` permission?

**Comment by cattaneod** [comment]
No, the person who used skip doesn't have that permission

**Comment by Mednoob** [comment]
I will investigate the problem, thank you for your report.

**Comment by Mednoob** [comment]
If you have any further information you want me to know, you can send it here.

**Comment by mzrtamp** [comment]
Please create new thread instead of commenting a bug report to this closed one.
