### ISSUE TITLE
[Features] Audio filtering system

### ISSUE THREAD

**Issue by SouvikUnscripted** [stegripe/rawon#477]
This is something we see in most of the music bots, but to be honest, there is a very little percentage of people who use this cool thing. Filters like bass-boost, nightcore, etc. - It is really fun to add filters in songs while playing them. - Thanks!
![image](https://user-images.githubusercontent.com/40933469/134678043-209980c8-e3b9-4b02-b62a-586cf69c6f51.png)

**Comment by Mednoob** [comment]
We'll consider about this. Thank you for the suggestion.

**Comment by mzrtamp** [comment]
Probably this won't land in 2.0.x

**Comment by SouvikUnscripted** [comment]
Oh, I feel a bit sad hearing this wouldn't land in 2.0. - But it's totally ok to have it in the future.

**Comment by satoufuyuki** [comment]
Wait until https://github.com/discordjs/voice/pull/198 released and stable

**Comment by mzrtamp** [comment]
We're confirming that this won't land in 3.0.x too. But don't worry, we're not gonna ignoring this request, sorry about it 🙏

**Comment by Mednoob** [comment]
This feature is now in-dev on #1105
