### ISSUE TITLE
[Features] Creating a GitHub Pages

### ISSUE THREAD

**Issue by Mednoob** [stegripe/rawon#489]
Yes, I'm planning to create a Github Pages for this project. Why? This will help people to access and use everything related to disc-11. This will be something that I will work on after v2 released. I still don't know exactly when and where to start. So, I'm just gonna leave this here as an issue.

**Comment by mzrtamp** [comment]
https://disc-11.zhycorp.net

**Comment by Mednoob** [comment]
To Do
- [x] Move all assets including google app script to GitHub Pages

**Comment by Mednoob** [comment]
It seems that Next.JS routing sucks since it blocked static js and css required for the page. So, we will use CRA again.
