### ISSUE TITLE
[Bug Report] Voice State Update doesn't work as expected

### ISSUE THREAD

**Issue by satoufuyuki** [stegripe/rawon#498]
Known bug:
- ~~When someone joined voice and bot still playing (no resumeTimeout), the bot will send a resumeTimeout message~~ [de475ce]
- `doTimeout` & `resumeTimeout` kinda buggy when the voice channel got deleted

**Comment by mzrtamp** [comment]
Fixed in [[`ee232b5`](https://github.com/zhycorp/disc-11/pull/460/commits/ee232b5b54fcc4e6436fb2999a38e3654b7b07d7)]
