### ISSUE TITLE
[Question] Installation error

### ISSUE THREAD

**Issue by ghost** [stegripe/rawon#587]
### Describe the bug

Require stack:

- /app/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    
   

### Operating System

linux

**Comment by ghost** [comment]
npm WARN reify Removing non-directory /app/node_modules
npm WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.

**Comment by mzrtamp** [comment]
> npm WARN reify Removing non-directory /app/node_modules
> npm WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.

This is a warn message, not a bug. Just ignore it and keep waiting.

**Comment by mzrtamp** [comment]
Ok, I guess that's all.
