### ISSUE TITLE
[Bug Report] Slash commands gives "Interaction failed" error

### ISSUE THREAD

**Issue by 21Z** [stegripe/rawon#595]
### Describe the bug

(slash cmd): it errors "Interaction failed" and the reply to the used slash cmd gets sent as a normal msg instead of a reply to the slash cmd
~~(buttons): It works as expected but it errors "Interaction Failed" for no reason~~ (fixed)

### To Reproduce

(slash cmd): Use a slash command.
~~(buttons): Click on a message button.~~

### Expected behavior

(slash cmd): the reply (message) should come as a reply to the slash command.
example:
![image](https://user-images.githubusercontent.com/69188068/140604854-7a69d586-a1a8-4e01-b75c-a373d35bb4c9.png)
~~(buttons): it should not say "Interaction Failed"~~

### Operating System

Linux

**Comment by 21Z** [comment]
This has been fixed in #618 (v2.2.0)

**Comment by 21Z** [comment]
This problem still exists...

**Comment by 21Z** [comment]
This problem still exists...

**Comment by Mednoob** [comment]
@21Z Can you tell me what were you trying to do before the `Interaction Failed` show up?

**Comment by 21Z** [comment]
While using a slash command...
The issue was fixed for buttons in v2.2 but it still exists with slash commands
![Screenshot_20211207-194348~2](https://user-images.githubusercontent.com/69188068/145045438-9a4ab14b-3559-4b0b-9c3f-b8f9db7e0feb.png)
Commands I used: /play query: idk
                                   /ping

**Comment by mzrtamp** [comment]
Maybe this were fixed in [`v3`](https://github.com/Clytage/rawon/tree/feat/3.0.0), why "maybe"? Because we're no longer experiencing this again since it.
