### ISSUE TITLE
[Features] Add more unique URL from SoundCloud (Android's redirect URL)

### ISSUE THREAD

**Issue by dominicrude** [stegripe/rawon#613]
### Is your feature request related to a problem? Please describe.

When i copy url from android, this link https://soundcloud.app.goo.gl/Mr2m4 cannot be play on your bot, and bot's respon like picture below
![unknown-3](https://user-images.githubusercontent.com/94474671/142183809-ffe330a4-a862-4f19-972f-dd00713419d6.png)
Thanks, regards.

### Describe the solution you'd like

I hope, the bot can play every unique link from Soundcloud and another platform, thanks.

**Comment by Mednoob** [comment]
Fixed in #618
