### ISSUE TITLE
[Features] More flexible prefix usage

### ISSUE THREAD

**Issue by dominicrude** [stegripe/rawon#614]
### Is your feature request related to a problem? Please describe.

I set the prefix with alphabet, in this case, i use "W", but when i type with "w", bot not respond like picture below
![unknown-4](https://user-images.githubusercontent.com/94474671/142185231-f8d58375-85dd-4c69-addb-00fadf4bd8e7.png)
![unknown-5](https://user-images.githubusercontent.com/94474671/142185273-f9ef587d-acab-4426-b621-19d9beb4583d.png)

### Describe the solution you'd like

Bot can respon when i use the alphabetic prefix, whatever i type with UpperCase or LowerCase. Thanks.

**Comment by Mednoob** [comment]
Added multiple prefix feature in #618
