### ISSUE TITLE
[Question] Voteskip command not working

### ISSUE THREAD

**Issue by cattaneod** [stegripe/rawon#629]
### Describe the bug

Everyone can skip the current track without voting, even without DJ role

### Expected behavior

People without DJ role and which didn't request the current song should trigger a vote skip

### Operating System

Linux

**Comment by mzrtamp** [comment]
> It works normally as expected
> ![image](https://user-images.githubusercontent.com/40928387/146668358-4a3bdd4a-7a9b-4d7c-a8ee-c7721ca69d0a.png)

> Then I tried to give him a DJ role
> ![image](https://user-images.githubusercontent.com/40928387/146668375-e7cc0a6f-4ef0-440e-843f-87011d4cd468.png)
> ![image](https://user-images.githubusercontent.com/40928387/146668378-b397f099-2949-45ca-b8e1-71a59e139ada.png)

Make sure you have used the latest version.
