### ISSUE TITLE
[Bug Report] The queue actually ends when it starts

### ISSUE THREAD

**Issue by mzrtamp** [stegripe/rawon#642]
### Describe the bug

So it's been a long time since I've been experiencing this error myself, which when I tried to debug as much as possible, and it gave zero results aka console didn't give any results. But I've seen one of the errors that I encountered which may have something to do with here.

### To Reproduce

1. Run `play` command
2. There is ~~50/50~~ 90/50 chance you get the error

### Expected behavior

Played smooth, normally, messin' up the queue

### Screenshots

![image](https://user-images.githubusercontent.com/40928387/145317021-fa26f321-afc3-44ba-9cff-aa0172df2b04.png)

![image](https://user-images.githubusercontent.com/40928387/145317122-848c7b93-0b91-49b5-a49e-0ce6b998bbb3.png)

### Operating System

Linux

### Additional context

Please fix this ASAP (i'm not gonna forcing ☹️)

**Comment by 21Z** [comment]
From my experience, this problem occurs with some hosts that are really really cheap and free (mainly repl.it), the bot works good on some hosts.

**Comment by mzrtamp** [comment]
> From my experience, this problem occurs with some hosts that are really really cheap (mainly repl.it), the bot works good on some hosts.

No, I did it on my mid-end specification VPS, so I've decided this were a memory leak bug or idk.

**Comment by mzrtamp** [comment]
I'll close this since it going normal _for now_.
