### ISSUE TITLE
[Bug Report] Eval command doesn't work on Glitch

### ISSUE THREAD

**Issue by 21Z** [stegripe/rawon#643]
### Describe the bug

Eval command doesn't work on glitch, it acts like there's no command like that.

### To Reproduce

Use the eval command

### Expected behavior

It should work 

### Operating System

Linux

### Additional context

I filled all dev configs in ENV for the eval command, tried remixing it many times, ran enough tests, I can confirm it doesn't work on glitch..

**Comment by mzrtamp** [comment]
Did you have tried remixing it?

**Comment by 21Z** [comment]
yes

**Comment by Mednoob** [comment]
@21Z Can you show us the plain text of your `OWNERS` env value?

**Comment by 21Z** [comment]
![Uploading Screenshot_20211209-212742~2.png…]()

**Comment by 21Z** [comment]
![Screenshot_20211209-213032~2](https://user-images.githubusercontent.com/69188068/145431366-d13d9a9d-7794-4d6a-88a0-ebfafbf243bd.png)

**Comment by 21Z** [comment]
+ I think you or someone on the Zhycorp discord server tested this on the tutorial bot used in the yt channel, and this issue was there.

**Comment by Mednoob** [comment]
Not really. Before we merged the bot to main branch, I have tested the eval command and it's working normally (both in glitch and local environment).

**Comment by mzrtamp** [comment]
I have tested it too.
