### ISSUE TITLE
[Bug Report] Search command not working

### ISSUE THREAD

**Issue by SouvikUnscripted** [stegripe/rawon#652]
### Describe the bug

Search command doesn't work, when I use the command it shows me all the time.
![image](https://user-images.githubusercontent.com/40933469/146415713-887e48ac-61f0-47b9-bdf6-b413433594f9.png)

and in console
![image](https://user-images.githubusercontent.com/40933469/146415909-64d8c5cf-b911-4e5c-bc1b-302068ba866b.png)

### To Reproduce

1. Use the command "search".
2. Select the song from the results.
3. Encounter the issue.

### Expected behavior

The song should start playing normally.

### Screenshots

![image](https://user-images.githubusercontent.com/40933469/146416106-99eace1f-6e9c-4c18-ab6a-878a21fb7e3a.png)
![image](https://user-images.githubusercontent.com/40933469/146416120-76fb237d-f092-404f-9990-d218671baa0e.png)

### Operating System

Windows

**Comment by mzrtamp** [comment]
Fixed in #635 [[`754cba3`](https://github.com/zhycorp/disc-11/commit/754cba35b78857c4943b504dc40286d74a2e0ab2)]
