### ISSUE TITLE
[Bug Report] Search command is doing an infinity thinking

### ISSUE THREAD

**Issue by fab1ofx** [stegripe/rawon#781]
### Describe the bug

Search Command is unable to add song if the bot is not in a Voice Channel, but adding song can only be done when the bot is in a Voice Channel or currently playing songs.

Search Command only responds with something like "**Rawon** is typing" and the bot is unable to edit the message to something like song list after song has been added.

### Screenshots

![Screenshot_20220219-180256](https://user-images.githubusercontent.com/45721915/154799253-e746c178-d5e7-4f13-b7ed-5e9ef9ae4b3d.png)

### Operating System

Linux

**Comment by mzrtamp** [comment]
The song is still added to the queue when using this command, so I can explain that-

**Comment by fab1ofx** [comment]
> The song is still added to the queue when using this command, so I can explain that

yes, but queue command no song list if bot is not on voice channels

**Comment by mzrtamp** [comment]
![image](https://user-images.githubusercontent.com/40928387/169494628-adb59e14-035e-48be-8969-46ccc33e5676.png)
![image](https://user-images.githubusercontent.com/40928387/169494709-5b1e1c9d-8cce-405b-8604-3d547bd4b31f.png)
We found this, but we still figuring it out.

**Comment by mzrtamp** [comment]
This is known issue, and fixed already in [`v3`](https://github.com/Clytage/rawon/tree/feat/3.0.0). Let us know if this error still happens.
