### ISSUE TITLE
[Bug Report] Repeat command detail usage are not showing the actual value

### ISSUE THREAD

**Issue by 21Z** [stegripe/rawon#790]
### Is your feature request related to a problem? Please describe.

no

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/69188068/155453507-997cedd6-5572-410d-adcf-32a232d33bee.png)
add what these {options} are in help command
some people don't know how to use this command.
they just type xrepeat on. but it doesn't work so they try typing xhelp repeat (to know how to use it) but they can't find the options so it'd be better if u add something of the options in help command too

### Additional context

(sorry, i dont know how to explain this properly, I hope you understood)

**Comment by Mednoob** [comment]
I think I know what's wrong. We did put options explanation. But, @mzrtamp used wrong function for replacing the format (more info on [`7fd66f2`](https://github.com/Rahagia/rawon/commit/7fd66f2054a13a723ab31a7c638bdea6b04cdedd)). We're sorry about that and will fix it soon.

**Comment by Mednoob** [comment]
Also, I will add an information as to how to change repeat mode in the no-args repeat embed footer.

**Comment by mzrtamp** [comment]
I haven't noticed much
