### ISSUE TITLE
[Features] Don't reset the Volume command when the track is ended

### ISSUE THREAD

**Issue by mzrtamp** [stegripe/rawon#830]
### Is your feature request related to a problem? Please describe.

It doesn't feel good if every song queue changes or ends, the queue volume is immediately reset to default or 100.

### Describe the solution you'd like

As the title said.

**Comment by Mednoob** [comment]
Feature added in commit [`a680b13`](https://github.com/Rahagia/rawon/pull/753/commits/a680b13a93c70cf152e534de6cfada2dff5203de)
