### ISSUE TITLE
[Bug Report] YouTube URLs is not working

### ISSUE THREAD

**Issue by Septem151** [stegripe/rawon#856]
On v2.1.0, YouTube links (whether it's youtube.com or youtu.be) do not work anymore. The result is "That URL doesn't have any song data." with no messages on the log. However, Spotify links work, as well as typing in the name of the song.

I tried updating to v2.4.0, but the bot doesn't respond to commands at all when doing this, so v1.4.0 does not work at all for me. Again, no error messages in the logs.

**Comment by Mednoob** [comment]
Thanks you for noticing us 👍. It should be fixed in v3.

**Comment by mzrtamp** [comment]
`prio: mid`

**Comment by mzrtamp** [comment]
It solved. We're testing all of the youtube links variant, and no any error happens, it-just-works.
