### ISSUE TITLE
[Bug Report] Spotify playlist links is not working

### ISSUE THREAD

**Issue by ghost** [stegripe/rawon#932]
### Describe the bug

![image](https://user-images.githubusercontent.com/90360099/168469867-5274649e-a5af-441c-83cc-77d38285ba4a.png)
I try and play a link on my Spotify playlist and it says this 

### Operating System

windows 10

**Comment by mzrtamp** [comment]
This is known issue, and fixed already in [`v3`](https://github.com/Clytage/rawon/tree/feat/3.0.0). Let us know if this error still happens

**Comment by mzrtamp** [comment]
This is known issue, and fixed already in [`v3`](https://github.com/Clytage/rawon/tree/feat/3.0.0). Let us know if this error still happens.

**Comment by mzrtamp** [comment]
I've confirmed this issue is solved in [`v3`](https://github.com/Clytage/rawon/tree/feat/3.0.0)

![image](https://user-images.githubusercontent.com/40928387/169484674-d3c46b39-1ad5-4fd8-b8c5-549dcb902025.png)

**Comment by mzrtamp** [comment]
We will make this pre-version is stable-released ASAP 😉
