### ISSUE TITLE
[Bug Report] Spotify playlist links is not working

### ISSUE THREAD

**Issue by ghost** [stegripe/rawon#936]
### Is your feature request related to a problem? Please describe.

there is no spotify playlist link support

### Describe the solution you'd like

add spotify playlist link support

### Describe alternatives you've considered

~p https://open.spotify.com/playlist/1XcIfqCd5JNOojr69ZIQcZ?si=6445336dc6654ae4

### Additional context

:)

**Comment by Mednoob** [comment]
What version did you use?

**Comment by mzrtamp** [comment]
#932
