### ISSUE TITLE
[Bug Report] 401 (Unauthorized) on Lyrics command

### ISSUE THREAD

**Issue by mzrtamp** [stegripe/rawon#939]
### Describe the bug

Lyrics command is using API thingy from @lxndr-rl, which is causing an issue. The actual one is, now his API is requiring authorization method, that bit annoying for future Rawon users, I need his hand to consider, handle, and getting a solution for this issue.

### To Reproduce

1. Use `lyrics` command
2. Command is not working as expected
3. The error should appear in console

### Expected behavior

It-just-works by using this command, then specify the title of the song that you want to see.

### Screenshots

![image](https://user-images.githubusercontent.com/40928387/169865807-f990febc-b840-4000-8c4f-406d2346b7ef.png)

### Operating System

Windows

### Additional context

This issue should be solved before [`v3`](https://github.com/Clytage/rawon/tree/feat/3.0.0) released.

**Comment by lxndr-rl** [comment]
I just added Rawon to a white list, it is MANDATORY to define that it is **DiscordRawon**, otherwise it will answer unauthorized.

`/lyrics?song=${encodeURI(song)}&from=DiscordRawon`

**Comment by mzrtamp** [comment]
Ok, we will look forward on this 👍

**Comment by mzrtamp** [comment]
This command now is working how it usually works, thank you.
