### ISSUE TITLE
[Bug Report] DEV environment file disappears in Glitch

### ISSUE THREAD

**Issue by 21Z** [stegripe/rawon#946]
### Describe the bug

The dev.env disappears once it is renamed to dev.env from dev.env_example
because of gitignore
![image](https://user-images.githubusercontent.com/69188068/171252056-2f5162b5-342d-4d89-8ec8-a41552b05fc3.png)

### Operating System

linux

**Comment by mzrtamp** [comment]
@Mednoob How do you think?

**Comment by mzrtamp** [comment]
@Mednoob How do you think?

**Comment by Mednoob** [comment]
Hmmm, maybe I should add automation for the .gitignore content in `index.js` so that the code will automatically remove dev.env from .gitignore if the bot startup on glitch
