### ISSUE TITLE
[Bug Report] Spotify playlist doesn't have any song data

### ISSUE THREAD

**Issue by urfavteddybear** [stegripe/rawon#971]
### Describe the bug

Hi, idk if this is a bug or not but if i trying to play my own spotify playlist, it always said `That URL doesn't have any song data.` and if i add a official spotify playlist, it runs perfectly (play-dl stream strategy).

### To Reproduce

1. run play command with spotify playlist
2. see the error

### Expected behavior

i expect the bot will add the playlist to the queue

### Screenshots

https://user-images.githubusercontent.com/97431620/179397849-b425dc6a-f959-43c6-b8cb-100c6b9676c9.png

### Operating System

Linux

**Comment by Mednoob** [comment]
What version did you use when this error happened?

**Comment by urfavteddybear** [comment]
> What version did you use when this error happened?

![image](https://user-images.githubusercontent.com/97431620/179398491-d97ca91c-1d52-4ab7-ba14-e2f5b5b839b9.png)
its 3.0.0 based on about command

**Comment by urfavteddybear** [comment]
is there any way to fix this problem?

**Comment by Mednoob** [comment]
woops, sorry. I forgot about this issue. Try restarting the bot.

**Comment by urfavteddybear** [comment]
> woops, sorry. I forgot about this issue. Try restarting the bot. 

already tried this, changed the bot hosting, reinstall the bot, and i still got the same problem. do you guys have any running instance that i can use to test?

**Comment by mzrtamp** [comment]
Honestly, I'm also experienced to what you are going through. I personally don't know exactly where the problem is, and this issue also certainly appears for some me and my friend's spotify playlists, so I don't know how to follow up on this issue.

**Comment by mzrtamp** [comment]
![2961534E-566D-4DDF-BB09-F143D6D701C6](https://user-images.githubusercontent.com/40928387/180766447-9bfb09d4-5014-4218-85d2-30a02136cc9f.jpeg)
![379284F1-F52A-454C-95AA-309556182857](https://user-images.githubusercontent.com/40928387/180766468-afa3e72b-448f-4720-b8f9-80818d89b392.jpeg)
![26E0ADE8-F339-4BC9-8FA2-2E221A9776B4](https://user-images.githubusercontent.com/40928387/180766474-b36a7cf8-cfea-41d3-a490-35f07b2e6de8.jpeg)

I have tried all kinds of spotify playlist sharing url parameters, and this playlists also work well with other bots. Sorry for not being able to help you right now, but I'll try to ask other developers to consider this issue.

**Comment by noxzym** [comment]
@urfavteddybear Your issue have been fixed since PR #981 merged.

**Comment by urfavteddybear** [comment]
> @urfavteddybear Your issue have been fixed since PR #981 merged.

Thank you for the PR, it works now but the song that added from spotify playlist isn't organized well.
![image](https://user-images.githubusercontent.com/97431620/181225672-c99220ea-ef85-42aa-a8be-32c670f9a7fa.png)

**Comment by noxzym** [comment]
> > @urfavteddybear Your issue have been fixed since PR #981 merged.
> 
> Thank you for the PR, it works now but the song that added from spotify playlist isn't organized well. ![image](https://user-images.githubusercontent.com/97431620/181225672-c99220ea-ef85-42aa-a8be-32c670f9a7fa.png)

yeah ik, next time i'll try to fix that

**Comment by mzrtamp** [comment]
Just address it into #949

**Comment by urfavteddybear** [comment]
> Just address it into #949 

Did that PR fix the Spotify and the unorganized songs bug?

**Comment by mzrtamp** [comment]
The fix you want should land in that version soon.

**Comment by urfavteddybear** [comment]
> The fix you want should land in that version soon.

Alright, hope it will be fixed soon.
